# Find full documentation here https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
name: PR

on:
  pull_request:

  # Manual invocation.
  workflow_dispatch:

  push:
    branches:
      - "main"
jobs:
  PR:
    runs-on: ubuntu-latest

    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: 'sbt'

      - name: Run tests
        run: ./script/test
